global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: model-gateway
    static_configs:
      - targets: ["model-gateway:8001"]

  - job_name: document-svc
    static_configs:
      - targets: ["document-svc:8002"]

  - job_name: evaluation-svc
    static_configs:
      - targets: ["evaluation-svc:8003"]

  - job_name: job-runner
    static_configs:
      - targets: ["job-runner:8004"]
